feat: adding annotation to define reconciliation frequency
validator-labs/validator-plugin-oci pull request #297
Opened 2024-09-17 14:48 UTC by ADorigi

## Issue
partially resolves validator-labs/validator#358

## Description

- I have added a sample showing how to use the annotation `validation.validator.labs/reconciliation-frequency`.
- The annotation value is an `integer` representing the time in `seconds`.
- I added a constant to define the annotation key.
- The controller checks if the annotation has been defined. If it finds the annotation, it uses that. If it doesn't find the annotation, it takes `120` seconds as default.

2024-09-17 15:13 UTC, TylerGillson requested changes
@ADorigi thanks!

This is great, but please relocate the constant to the [validator core repo](https://github.com/validator-labs/validator) and add a helper there to construct a `ctrl.Result` given a slice of annotations. It can go under `pkg/plugins`. That way each plugin's controller can call the helper in the core repo to construct its result and we don't duplicate code.

Lastly, please do log the requeue delay so we know the annotation is working.

2024-09-29 20:41 UTC, ADorigi commented
@TylerGillson 
I have shifted the functionality to `validator core repo` as advised: validator-labs/validator#422

2024-11-22 19:32 UTC, TylerGillson commented
@ADorigi any plans to follow up on this? I'd like to reassign this feature, but wanted to check in first.

2024-11-22 20:13 UTC, ADorigi commented
@TylerGillson I am blocked by validator-labs/validator#424. I will update this PR once the helper in the 0.1.13 release of validator-labs/validator is accessible by the plugin repositories. Please advise if there is another way.

2024-11-22 22:41 UTC, TylerGillson commented
> @TylerGillson I am blocked by [validator-labs/validator#424](https://github.com/validator-labs/validator/pull/424). I will update this PR once the helper in the 0.1.13 release of validator-labs/validator is accessible by the plugin repositories. Please advise if there is another way.

Apologies for that... I didn't realize we hadn't cut a release with your validator changes! I just triggered a new release. It will be available shortly.

2024-11-27 03:35 UTC, ADorigi commented
Thank you @TylerGillson 
Since this branch is out of data, I will close this pull request and create a new one, at #327

2024-11-27 03:35 UTC, closed without merging